In [3]:
import pandas as pd
import os
from pathlib import Path

In [4]:
data_path = Path("data")

In [6]:
popfordeling_2023 = pd.read_csv(data_path / "startpop_no_test.csv")
popfordeling_2123 = pd.read_csv(data_path / "populasjon_2123_tfr1_5.csv")

In [7]:
popfordeling_2023

      sex  alder  barn
0       K      0     0
1       K      0     0
2       K      0     0
3       K      0     0
4       K      0     0
...    ..    ...   ...
54886   M    101     1
54887   K    102     2
54888   K    102     2
54889   K    103     2
54890   K    105     3

[54891 rows x 3 columns]

In [10]:
popfordeling_2023.barn.value_counts().sort_index()

barn
0    25397
1     6273
2    14292
3     6725
4     2204
Name: count, dtype: int64

In [11]:
popfordeling_2123.barn.value_counts().sort_index()

barn
0.0    2182063
1.0     442514
2.0     300407
3.0     133710
4.0      41517
5.0       9825
6.0       1800
7.0        260
8.0         32
9.0          2
Name: count, dtype: int64

In [115]:
def fix_barnetallsfordeling():
    barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=1, nrows=16, sep=";").reset_index(drop=True)
    info = barnetallsfordeling.iloc[0,0]
    kjønn = info.split(" ")[0]
    alder = int(info.split(" ")[-2])
    alder
    barnetallsfordeling["kjønn"] = kjønn.replace("s", "")
    barnetallsfordeling["alder"] = alder
    barnetallsfordeling.columns = ["årstall", "0 barn", "1 barn", "2 barn", "3 barn", "4 barn eller flere", "gjennomsnittlig barnetall", "kjønn", "alder"]
    barnetallsfordeling = barnetallsfordeling.iloc[1:]
    return barnetallsfordeling

In [117]:
barnetallsfordeling = fix_barnetallsfordeling()

barnetallsfordeling.to_csv(f"data_barnefordeling/{barnetallsfordeling['alder'].unique()[0]}_{barnetallsfordeling['kjønn'].unique()[0]}")

In [90]:
barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=17, nrows=15, sep=";").reset_index(drop=True)
barnetallsfordeling

                   2004  98,9  1,02  0,08    0  0,0  0,01
0   Kvinnes alder 25 år   NaN   NaN   NaN  NaN  NaN   NaN
1                  1935  36,9  31,2  24,2  6,4  1,3  1,04
2                  1940  34,8  28,5  26,4  8,1  2,2  1,14
3                  1945  33,3  29,4  27,3  8,2  1,8  1,16
4                  1950  34,4  32,0  27,4  5,4  0,7  1,06
5                  1955  43,2  30,6  22,7  3,2  0,4  0,87
6                  1960  52,6  27,5  17,1  2,5  0,3  0,71
7                  1965  56,8  26,6  13,9  2,3  0,3  0,63
8                  1970  61,9  24,1  11,8  1,9  0,3  0,55
9                  1975  68,0  20,7   9,3  1,7  0,3  0,46
10                 1980  71,5  18,9   7,9  1,4  0,3  0,40
11                 1985  71,7  19,0   7,7  1,3  0,3  0,39
12                 1990  76,4  15,8   6,7  1,0  0,2  0,33
13                 1995  83,5  11,2   4,5  0,7  0,1  0,23
14                 1999  88,5   8,0   2,9  0,5  0,1  0,16

In [96]:
barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=17, nrows=15, sep=";").reset_index(drop=True)
barnetallsfordeling

                   2004  98,9  1,02  0,08    0  0,0  0,01
0   Kvinnes alder 25 år   NaN   NaN   NaN  NaN  NaN   NaN
1                  1935  36,9  31,2  24,2  6,4  1,3  1,04
2                  1940  34,8  28,5  26,4  8,1  2,2  1,14
3                  1945  33,3  29,4  27,3  8,2  1,8  1,16
4                  1950  34,4  32,0  27,4  5,4  0,7  1,06
5                  1955  43,2  30,6  22,7  3,2  0,4  0,87
6                  1960  52,6  27,5  17,1  2,5  0,3  0,71
7                  1965  56,8  26,6  13,9  2,3  0,3  0,63
8                  1970  61,9  24,1  11,8  1,9  0,3  0,55
9                  1975  68,0  20,7   9,3  1,7  0,3  0,46
10                 1980  71,5  18,9   7,9  1,4  0,3  0,40
11                 1985  71,7  19,0   7,7  1,3  0,3  0,39
12                 1990  76,4  15,8   6,7  1,0  0,2  0,33
13                 1995  83,5  11,2   4,5  0,7  0,1  0,23
14                 1999  88,5   8,0   2,9  0,5  0,1  0,16

In [97]:
barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=17+15, nrows=14, sep=";").reset_index(drop=True)
barnetallsfordeling

                   1999  88,5   8,0   2,9   0,5  0,1  0,16
0   Kvinnes alder 30 år   NaN   NaN   NaN   NaN  NaN   NaN
1                  1935  16,9  18,5  35,5  20,2  8,9  1,86
2                  1940  15,8  16,8  36,0  22,0  9,3  1,92
3                  1945  15,2  18,4  41,3  19,1  5,9  1,82
4                  1950  16,9  21,1  44,8  14,3  2,9  1,65
5                  1955  22,4  23,9  39,4  12,1  2,3  1,48
6                  1960  26,2  25,1  34,8  11,7  2,3  1,39
7                  1965  29,4  25,7  32,1  10,6  2,1  1,31
8                  1970  33,8  26,2  29,1   9,0  1,9  1,19
9                  1975  39,2  26,3  25,6   7,2  1,7  1,06
10                 1980  41,1  27,3  23,5   6,5  1,6  1,01
11                 1985  43,4  26,1  23,0   6,0  1,5  0,97
12                 1990  49,9  23,8  20,3   4,9  1,1  0,84
13                 1994  56,3  21,4  17,6   4,0  0,7  0,71

In [122]:
def fix_barnetallsfordeling(ant_skip, ant_rows):
    barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=ant_skip, nrows=ant_rows, sep=";").reset_index(drop=True)
    info = barnetallsfordeling.iloc[0,0]
    kjønn = info.split(" ")[0]
    alder = int(info.split(" ")[-2])
    alder
    barnetallsfordeling["kjønn"] = kjønn.replace("s", "")
    barnetallsfordeling["alder"] = alder
    barnetallsfordeling.columns = ["årstall", "0 barn", "1 barn", "2 barn", "3 barn", "4 barn eller flere", "gjennomsnittlig barnetall", "kjønn", "alder"]
    barnetallsfordeling = barnetallsfordeling.iloc[1:]
    return barnetallsfordeling

In [111]:
barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=31, nrows=13, sep=";").reset_index(drop=True)
barnetallsfordeling

                   1995  83,5  11,2   4,5   0,7  0,1  0,23
0                  1999  88,5   8,0   2,9   0,5  0,1  0,16
1   Kvinnes alder 30 år   NaN   NaN   NaN   NaN  NaN   NaN
2                  1935  16,9  18,5  35,5  20,2  8,9  1,86
3                  1940  15,8  16,8  36,0  22,0  9,3  1,92
4                  1945  15,2  18,4  41,3  19,1  5,9  1,82
5                  1950  16,9  21,1  44,8  14,3  2,9  1,65
6                  1955  22,4  23,9  39,4  12,1  2,3  1,48
7                  1960  26,2  25,1  34,8  11,7  2,3  1,39
8                  1965  29,4  25,7  32,1  10,6  2,1  1,31
9                  1970  33,8  26,2  29,1   9,0  1,9  1,19
10                 1975  39,2  26,3  25,6   7,2  1,7  1,06
11                 1980  41,1  27,3  23,5   6,5  1,6  1,01
12                 1985  43,4  26,1  23,0   6,0  1,5  0,97

In [114]:
ant_rows = 0
ant_skip = 17
for i in range (2,10):
    ant_skip += ant_rows
    ant_rows = 17 - i
    print(ant_skip, ant_rows)
    barnetallsfordeling = fix_barnetallsfordeling(ant_skip, ant_rows)
    #barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=ant_skip, nrows=ant_rows, sep=";").reset_index(drop=True)
    barnetallsfordeling.to_csv(f"data_barnefordeling/{barnetallsfordeling['alder'].unique()[0]}_{barnetallsfordeling['kjønn'].unique()[0]}")
    print(barnetallsfordeling)

17 15
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1935   36,9   31,2   24,2    6,4                1,3
2     1940   34,8   28,5   26,4    8,1                2,2
3     1945   33,3   29,4   27,3    8,2                1,8
4     1950   34,4   32,0   27,4    5,4                0,7
5     1955   43,2   30,6   22,7    3,2                0,4
6     1960   52,6   27,5   17,1    2,5                0,3
7     1965   56,8   26,6   13,9    2,3                0,3
8     1970   61,9   24,1   11,8    1,9                0,3
9     1975   68,0   20,7    9,3    1,7                0,3
10    1980   71,5   18,9    7,9    1,4                0,3
11    1985   71,7   19,0    7,7    1,3                0,3
12    1990   76,4   15,8    6,7    1,0                0,2
13    1995   83,5   11,2    4,5    0,7                0,1
14    1999   88,5    8,0    2,9    0,5                0,1

   gjennomsnittlig barnetall   kjønn  alder
1                       1,04  Kvinne     25
2                       1,14  Kvinne     25
3                       1,16  Kvinne     25
4                       1,06  Kvinne     25
5                       0,87  Kvinne     25
6                       0,71  Kvinne     25
7                       0,63  Kvinne     25
8                       0,55  Kvinne     25
9                       0,46  Kvinne     25
10                      0,40  Kvinne     25
11                      0,39  Kvinne     25
12                      0,33  Kvinne     25
13                      0,23  Kvinne     25
14                      0,16  Kvinne     25
32 14
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1935   16,9   18,5   35,5   20,2                8,9
2     1940   15,8   16,8   36,0   22,0                9,3
3     1945   15,2   18,4   41,3   19,1                5,9
4     1950   16,9   21,1   44,8   14,3                2,9
5     1955   22,4   23,9   39,4   12,1                2,3
6     1960   26,2   25,1   34,8   11,7                2,3
7     1965   29,4   25,7   32,1   10,6                2,1
8     1970   33,8   26,2   29,1    9,0                1,9
9     1975   39,2   26,3   25,6    7,2                1,7
10    1980   41,1   27,3   23,5    6,5                1,6
11    1985   43,4   26,1   23,0    6,0                1,5
12    1990   49,9   23,8   20,3    4,9                1,1
13    1994   56,3   21,4   17,6    4,0                0,7

   gjennomsnittlig barnetall   kjønn  alder
1                       1,86  Kvinne     30
2                       1,92  Kvinne     30
3                       1,82  Kvinne     30
4                       1,65  Kvinne     30
5                       1,48  Kvinne     30
6                       1,39  Kvinne     30
7                       1,31  Kvinne     30
8                       1,19  Kvinne     30
9                       1,06  Kvinne     30
10                      1,01  Kvinne     30
11                      0,97  Kvinne     30
12                      0,84  Kvinne     30
13                      0,71  Kvinne     30
46 13
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1935   11,2   11,9   32,0   26,8               18,1
2     1940   11,0   11,3   34,2   28,0               15,4
3     1945   10,6   12,8   42,2   25,2                9,1
4     1950   11,6   15,0   45,8   21,5                6,0
5     1955   14,5   16,6   42,6   21,0                5,4
6     1960   15,9   16,7   39,3   22,0                6,1
7     1965   17,3   17,5   39,0   20,5                5,6
8     1970   19,6   18,8   38,7   18,3                4,8
9     1975   21,6   19,5   37,9   16,6                4,5
10    1980   22,8   20,9   37,4   14,9                4,0
11    1985   24,7   20,9   37,6   13,2                3,6
12    1989   28,4   20,6   35,6   12,5                3,0

   gjennomsnittlig barnetall    kjønn  alder
1                       2,29  Kvinnen     35
2                       2,26  Kvinnen     35
3                       2,09  Kvinnen     35
4                       1,95  Kvinnen     35
5                       1,86  Kvinnen     35
6                       1,87  Kvinnen     35
7                       1,82  Kvinnen     35
8                       1,72  Kvinnen     35
9                       1,65  Kvinnen     35
10                      1,58  Kvinnen     35
11                      1,51  Kvinnen     35
12                      1,42  Kvinnen     35
59 12
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1935    9,8   10,5   30,4   27,4               21,8
2     1940    9,7   10,1   33,9   29,0               17,3
3     1945    9,2   11,9   41,6   26,3               11,0
4     1950    9,7   13,5   45,4   23,3                8,0
5     1955   11,7   14,6   42,1   23,9                7,7
6     1960   12,6   14,2   39,2   25,3                8,8
7     1965   13,3   14,4   40,0   24,3                7,9
8     1970   14,3   15,2   40,9   22,6                7,2
9     1975   15,3   15,7   41,1   21,3                6,5
10    1980   16,5   17,2   41,2   19,4                5,8
11    1984  17,74   17,4   41,5   17,9               5,43

   gjennomsnittlig barnetall    kjønn  alder
1                       2,41  Kvinnen     40
2                       2,34  Kvinnen     40
3                       2,18  Kvinnen     40
4                       2,06  Kvinnen     40
5                       2,01  Kvinnen     40
6                       2,07  Kvinnen     40
7                       2,02  Kvinnen     40
8                       1,96  Kvinnen     40
9                       1,91  Kvinnen     40
10                      1,83  Kvinnen     40
11                      1,78  Kvinnen     40
71 11
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1935    9,6   10,4   30,4   27,4               22,2
2     1940    9,5   10,1   33,7   29,1               17,6
3     1945    9,0   11,8   41,5   26,4               11,3
4     1950    9,4   13,3   45,4   23,5                8,4
5     1955   11,2   14,3   42,1   24,2                8,1
6     1960   11,9   13,8   39,4   25,6                9,2
7     1965   12,5   14,2   40,2   24,7                8,4
8     1970   13,4   14,7   41,2   23,1                7,6
9     1975   14,2   15,3   41,7   21,8                7,0
10    1979   15,4   16,4   41,6   20,1                6,5

   gjennomsnittlig barnetall    kjønn  alder
1                       2,42  Kvinnen     45
2                       2,35  Kvinnen     45
3                       2,19  Kvinnen     45
4                       2,08  Kvinnen     45
5                       2,04  Kvinnen     45
6                       2,10  Kvinnen     45
7                       2,06  Kvinnen     45
8                       2,00  Kvinnen     45
9                       1,96  Kvinnen     45
10                      1,89  Kvinnen     45
82 10
  årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1    1940   95,3    4,3    0,4    0,0                0,0
2    1945   94,1    5,3    0,6    0,0                0,0
3    1950   93,5    5,8    0,6    0,0                0,0
4    1955   94,0    5,8    0,3    0,0                0,0
5    1960   96,9    3,0    0,1    0,0                0,0
6    1965   97,6    2,4    0,1    0,0                0,0
7    1970   97,6    2,3    0,1    0,0                0,0
8    1975   98,2    1,7    0,1    0,0                0,0
9    1980   98,2    1,7    0,1    0,0                0,0

  gjennomsnittlig barnetall   kjønn  alder
1                      0,05  Mannen     20
2                      0,07  Mannen     20
3                      0,07  Mannen     20
4                      0,06  Mannen     20
5                      0,03  Mannen     20
6                      0,03  Mannen     20
7                      0,03  Mannen     20
8                      0,02  Mannen     20
9                      0,02  Mannen     20
92 9

IndexError: list index out of range

In [138]:
barnetallsfordeling = fix_barnetallsfordeling(82, 15)
barnetallsfordeling.to_csv(f"data_barnefordeling/{barnetallsfordeling['alder'].unique()[0]}_{barnetallsfordeling['kjønn'].unique()[0]}")

In [139]:
ant_rows = 0
ant_skip = 82
for i in range (2,10):
    ant_skip += ant_rows
    ant_rows = 17 - i
    print(ant_skip, ant_rows)
    barnetallsfordeling = fix_barnetallsfordeling(ant_skip, ant_rows)
    #barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=ant_skip, nrows=ant_rows, sep=";").reset_index(drop=True)
    barnetallsfordeling.to_csv(f"data_barnefordeling/{barnetallsfordeling['alder'].unique()[0]}_{barnetallsfordeling['kjønn'].unique()[0]}")
    print(barnetallsfordeling)

82 15
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1940   95,3    4,3    0,4    0,0                0,0
2     1945   94,1    5,3    0,6    0,0                0,0
3     1950   93,5    5,8    0,6    0,0                0,0
4     1955   94,0    5,8    0,3    0,0                0,0
5     1960   96,9    3,0    0,1    0,0                0,0
6     1965   97,6    2,4    0,1    0,0                0,0
7     1970   97,6    2,3    0,1    0,0                0,0
8     1975   98,2    1,7    0,1    0,0                0,0
9     1980   98,2    1,7    0,1    0,0                0,0
10    1985   98,7    1,2    0,1    0,0                0,0
11    1990   98,5    1,4    0,1    0,0                0,0
12    1995   99,0    1,0    0,1    0,0                0,0
13    2000   99,5    0,5    0,0    0,0                0,0
14    2004   99,7    0,3    0,0    0,0                0,0

   gjennomsnittlig barnetall   kjønn  alder
1                       0,05  Mannen     20
2                       0,07  Mannen     20
3                       0,07  Mannen     20
4                       0,06  Mannen     20
5                       0,03  Mannen     20
6                       0,03  Mannen     20
7                       0,03  Mannen     20
8                       0,02  Mannen     20
9                       0,02  Mannen     20
10                      0,01  Mannen     20
11                      0,02  Mannen     20
12                      0,01  Mannen     20
13                      0,00  Mannen     20
14                      0,00  Mannen     20
97 14
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1940   60,2   23,8   12,7    2,9                0,4
2     1945   55,5   26,3   14,7    3,1                0,4
3     1950   57,7   27,2   13,2    1,7                0,2
4     1955   66,7   23,1    9,4    0,7                0,1
5     1960   75,9   17,6    6,0    0,5                0,1
6     1965   78,4   16,2    4,8    0,6                0,1
7     1970   81,3   14,1    4,1    0,5                0,0
8     1975   85,5   11,0    3,1    0,3                0,1
9     1980   87,3    9,9    2,5    0,3                0,3
10    1985   87,0    9,9    2,6    0,3                0,1
11    1990   89,1    8,4    2,2    0,3                0,0
12    1995   92,7    5,7    1,5    0,2                0,0
13    1999   94,8    4,2    1,0    0,1                0,0

   gjennomsnittlig barnetall   kjønn  alder
1                       0,60  Mannen     25
2                       0,67  Mannen     25
3                       0,59  Mannen     25
4                       0,44  Mannen     25
5                       0,31  Mannen     25
6                       0,28  Mannen     25
7                       0,24  Mannen     25
8                       0,18  Mannen     25
9                       0,16  Mannen     25
10                      0,16  Mannen     25
11                      0,14  Mannen     25
12                      0,09  Mannen     25
13                      0,06  Mannen     25
111 13
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1940   28,5   21,1   32,3   13,8                4,3
2     1945   27,0   22,9   35,5   11,9                2,7
3     1950   31,2   24,9   34,6    8,1                1,2
4     1955   39,0   25,6   28,3    6,1                1,0
5     1960   46,2   24,8   22,4    5,6                1,0
6     1965   51,0   23,5   20,0    4,7                0,8
7     1970   55,3   22,9   17,0    4,0                0,8
8     1975   60,6   21,9   14,2    2,9                0,5
9     1980   61,6   21,5   13,6    2,8                0,6
10    1985   63,6   20,4   12,9    2,6                0,6
11    1990   68,0   18,3   11,4    2,1                0,3
12    1994   73,5   15,4    9,2    1,7                0,2

   gjennomsnittlig barnetall   kjønn  alder
1                       1,45  Mannen     30
2                       1,41  Mannen     30
3                       1,23  Mannen     30
4                       1,05  Mannen     30
5                       0,91  Mannen     30
6                       0,81  Mannen     30
7                       0,72  Mannen     30
8                       0,61  Mannen     30
9                       0,60  Mannen     30
10                      0,56  Mannen     30
11                      0,49  Mannen     30
12                      0,40  Mannen     30
124 12
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1940   18,2   12,8   36,7   22,8                9,6
2     1945   18,0   14,9   41,8   19,8                5,5
3     1950   20,5   17,0   41,7   16,5                4,3
4     1955   24,7   18,4   37,2   15,9                3,8
5     1960   29,9   18,6   32,3   15,3                3,9
6     1965   33,2   19,4   30,8   13,4                3,2
7     1970   35,7   20,4  28,78   11,1                2,8
8     1975   38,4   20,7   28,6   10,0                2,2
9     1980   40,3   20,4   27,7    9,2                2,3
10    1985   42,0   20,4   27,5    8,3                1,9
11    1989   45,3   19,8   25,9    7,6                1,4

   gjennomsnittlig barnetall   kjønn  alder
1                       1,96  Mannen     35
2                       1,81  Mannen     35
3                       1,68  Mannen     35
4                       1,57  Mannen     35
5                       1,46  Mannen     35
6                       1,35  Mannen     35
7                       1,26  Mannen     35
8                       1,18  Mannen     35
9                       1,14  Mannen     35
10                      1,08  Mannen     35
11                      1,00  Mannen     35
136 11
   årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1     1940   14,9   10,4   36,2   26,0               12,4
2     1945   14,9   12,4   41,1   23,3                8,3
3     1950   16,3   13,9   41,4   21,1                7,4
4     1955   19,2   14,7   37,4   21,4                7,4
5     1960   23,3   14,7   33,5   21,2                7,3
6     1965   25,7   15,5   33,7   19,1                6,0
7     1970   26,5   16,3   34,6   17,3                5,4
8     1975   28,8   16,4   34,1   16,3                4,4
9     1980   30,6   16,8   33,7   14,7                4,3
10    1984   32,1   16,4   34,7   13,2                3,6

   gjennomsnittlig barnetall   kjønn  alder
1                       2,15  Mannen     40
2                       2,01  Mannen     40
3                       1,92  Mannen     40
4                       1,86  Mannen     40
5                       1,77  Mannen     40
6                       1,66  Mannen     40
7                       1,61  Mannen     40
8                       1,53  Mannen     40
9                       1,47  Mannen     40
10                      1,41  Mannen     40
147 10
  årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1    1940   13,9   10,0   35,8   26,4               13,9
2    1945   13,3   11,5   40,4   24,3               10,5
3    1950   14,8   12,6   41,0   22,3                9,3
4    1955   17,2   13,5   37,1   23,1                9,2
5    1960   20,7   13,4   34,1   22,7                9,1
6    1965   22,9   14,3   34,1   20,8                7,9
7    1970   23,4   14,8   35,4   19,4                7,0
8    1975   25,5   15,0   35,7   18,0                5,8
9    1979   27,1   15,1   35,9   16,5                5,4

  gjennomsnittlig barnetall   kjønn  alder
1                      2,22  Mannen     45
2                      2,09  Mannen     45
3                      2,02  Mannen     45
4                      1,98  Mannen     45
5                      1,90  Mannen     45
6                      1,80  Mannen     45
7                      1,75  Mannen     45
8                      1,66  Mannen     45
9                      1,60  Mannen     45
157 9
  årstall 0 barn 1 barn 2 barn 3 barn 4 barn eller flere  \
1    1940   13,6    9,8   35,7   26,5               14,4
2    1945   13,3   11,5   40,4   24,3               10,5
3    1950   14,4   12,3   40,7   22,6               10,0
4    1955   16,6   13,2   37,1   23,3                9,9
5    1960   19,9   13,0   34,2   23,0                9,9
6    1965   22,0   13,9   34,2   21,2                8,7
7    1970   22,4   14,5   35,5   19,8                7,7
8    1974   23,6   14,6   36,0   18,9                6,9

  gjennomsnittlig barnetall   kjønn  alder
1                      2,25  Mannen     50
2                      2,12  Mannen     50
3                      2,06  Mannen     50
4                      2,01  Mannen     50
5                      1,95  Mannen     50
6                      1,84  Mannen     50
7                      1,80  Mannen     50
8                      1,74  Mannen     50
166 8

ValueError: invalid literal for int() with base 10: 'pr'

In [58]:
barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=16, nrows=16, sep=";").reset_index(drop=True)
info = barnetallsfordeling.iloc[0,0]
kjønn = info.split(" ")[0]
alder = int(info.split(" ")[-2])
alder
barnetallsfordeling["kjønn"] = kjønn.replace("s", "")
barnetallsfordeling["alder"] = alder
barnetallsfordeling.columns = ["årstall", "0 barn", "1 barn", "2 barn", "3 barn", "4 barn eller flere", "gjennomsnittlig barnetall", "kjønn", "alder"]
barnetallsfordeling = barnetallsfordeling.iloc[1:]
barnetallsfordeling

IndexError: list index out of range

In [50]:
info.split(" ")[-2]

'20'

In [26]:
barnetallsfordeling = pd.read_csv(data_path / "barnetallsfordeling.csv",skiprows=17, nrows=15, sep=";")
barnetallsfordeling

                   2004  98,9  1,02  0,08    0  0,0  0,01
0   Kvinnes alder 25 år   NaN   NaN   NaN  NaN  NaN   NaN
1                  1935  36,9  31,2  24,2  6,4  1,3  1,04
2                  1940  34,8  28,5  26,4  8,1  2,2  1,14
3                  1945  33,3  29,4  27,3  8,2  1,8  1,16
4                  1950  34,4  32,0  27,4  5,4  0,7  1,06
5                  1955  43,2  30,6  22,7  3,2  0,4  0,87
6                  1960  52,6  27,5  17,1  2,5  0,3  0,71
7                  1965  56,8  26,6  13,9  2,3  0,3  0,63
8                  1970  61,9  24,1  11,8  1,9  0,3  0,55
9                  1975  68,0  20,7   9,3  1,7  0,3  0,46
10                 1980  71,5  18,9   7,9  1,4  0,3  0,40
11                 1985  71,7  19,0   7,7  1,3  0,3  0,39
12                 1990  76,4  15,8   6,7  1,0  0,2  0,33
13                 1995  83,5  11,2   4,5  0,7  0,1  0,23
14                 1999  88,5   8,0   2,9  0,5  0,1  0,16