In [2]:
import pandas as pd

df = pd.read_excel("startpop_norge.xlsx")
df

                  Alder   Menn  Kvinner
0                  0 år  26681    25310
1                  1 år  29378    28037
2                  2 år  27958    26820
3                  3 år  28989    27466
4                  4 år  29454    27692
..                  ...    ...      ...
101              101 år     54      256
102              102 år     32      164
103              103 år     21       82
104              104 år      5       39
105  105 år eller eldre     28       76

[106 rows x 3 columns]

In [16]:
# Funksjon for å ekspandere DataFrame
def expand_rows(row):
    menn = pd.DataFrame({'Alder': [row['Alder']] * row['Menn'], 'Kjønn': ['Menn'] * row['Menn']})
    kvinner = pd.DataFrame({'Alder': [row['Alder']] * row['Kvinner'], 'Kjønn': ['Kvinner'] * row['Kvinner']})
    return pd.concat([menn, kvinner])

# Ekspandere DataFrame
expanded_df = pd.concat([expand_rows(row) for _, row in df.iterrows()], ignore_index=True)

In [17]:
expanded_df["alder"] = expanded_df["Alder"].str.split(" ").str[0].astype(int)
expanded_df

                      Alder    Kjønn  alder
0                      0 år     Menn      0
1                      0 år     Menn      0
2                      0 år     Menn      0
3                      0 år     Menn      0
4                      0 år     Menn      0
...                     ...      ...    ...
5488979  105 år eller eldre  Kvinner    105
5488980  105 år eller eldre  Kvinner    105
5488981  105 år eller eldre  Kvinner    105
5488982  105 år eller eldre  Kvinner    105
5488983  105 år eller eldre  Kvinner    105

[5488984 rows x 3 columns]

In [33]:
values = [0, 1, 2, 3, 4]

def get_kids(age):
    if age > 40:
        return random.choices(values, weights=[14.7, 16.5,41.3,20.7,6.8], k=1)[0]
    elif age > 35:
        return random.choices(values, weights=[17.6,17.2,41.7,18.2,5.3], k=1)[0]
    elif age > 30:
        return random.choices(values, weights=[26.7,21.2,36.4,12.5,3.2], k=1)[0]
    elif age > 25:
        return random.choices(values, weights=[87.6,8.5,3.3,0.5,0.1,], k=1)[0]
    elif age > 20:
        return random.choices(values, weights=[98.8, 1.1, 0.1, 0, 0], k=1)[0]
    elif age > 15:
        return random.choices(values, weights=[99.5, 0.5, 0, 0, 0], k=1)[0]
    else:
        return 0

In [34]:
expanded_df["barn"] = expanded_df.alder.apply(get_kids)

In [35]:
expanded_df

             sex  alder  barn
0           Menn      0     0
1           Menn      0     0
2           Menn      0     0
3           Menn      0     0
4           Menn      0     0
...          ...    ...   ...
5488979  Kvinner    105     2
5488980  Kvinner    105     2
5488981  Kvinner    105     2
5488982  Kvinner    105     3
5488983  Kvinner    105     1

[5488984 rows x 3 columns]

In [41]:
expanded_df

             sex  alder  barn
0           Menn      0     0
1           Menn      0     0
2           Menn      0     0
3           Menn      0     0
4           Menn      0     0
...          ...    ...   ...
5488979  Kvinner    105     2
5488980  Kvinner    105     2
5488981  Kvinner    105     2
5488982  Kvinner    105     3
5488983  Kvinner    105     1

[5488984 rows x 3 columns]

In [42]:
expanded_df.to_csv("startpop_no_master.csv", index=False)

In [43]:
expanded_df.groupby(["alder", "sex"]).barn.count().sort_index().reset_index().rename(columns={"barn":f"pop_{2023}"})#

     alder      sex  pop_2023
0        0  Kvinner     25310
1        0     Menn     26681
2        1  Kvinner     28037
3        1     Menn     29378
4        2  Kvinner     26820
..     ...      ...       ...
207    103     Menn        21
208    104  Kvinner        39
209    104     Menn         5
210    105  Kvinner        76
211    105     Menn        28

[212 rows x 3 columns]

In [21]:
import random

expanded_df = expanded_df[["Kjønn","alder"]]
expanded_df.columns = ["sex", "alder"]
expanded_df["barn"] = list_of_kids

KeyError: "['Kjønn'] not in index"

In [45]:
expanded_df["sex"] = expanded_df["sex"].str.replace("Menn", "M").str.replace("Kvinner", "K")
expanded_df

        sex  alder  barn
0         M      0     0
1         M      0     0
2         M      0     0
3         M      0     0
4         M      0     0
...      ..    ...   ...
5488979   K    105     2
5488980   K    105     2
5488981   K    105     2
5488982   K    105     3
5488983   K    105     1

[5488984 rows x 3 columns]

In [46]:
expanded_df.to_csv("startpop_no.csv", index=False)

In [ ]:
)=